In [1]:
import numpy as np

In [2]:
a = np.linspace(1, 4, 4)

In [3]:
a[1:-1]

array([2., 3.])

In [8]:
A = np.matrix(np.ones([3,3]))

In [9]:
A

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
A.dot(np.array([1, 2, 4]))

matrix([[7., 7., 7.]])